# Define a keyword-to-menu mapping as a dictionary

KEYWORD_MAP = {
    # About us - Select
    "about us": "About Us",
    "about the team": "About Us",
    "company info": "About Us",
    "our mission": "About Us",
    "mission statement": "About Us",
    "learn about us": "About Us",
    "what we do": "About Us",
    "about this server": "About Us",
    "community info": "About Us",
    "why we're here": "About Us",
    "what we're about": "About Us",
    "team overview": "About Us",
    "team story": "About Us",

    # Who are we - Embed
    "who are we": "Who are we?",
    "who's behind this": "Who are we?",
    "who runs this": "Who are we?",
    "what is this server": "Who are we?",
    "what is this place": "Who are we?",
    "we are about": "Who are we?",
    "who made this": "Who are we?",
    "who created this": "Who are we?",
    "who owns this": "Who are we?",
    "our story": "Who are we?",
    "who's in charge": "Who are we?",
    "who's the team": "Who are we?",
    "who started this": "Who are we?",
    "server background": "Who are we?",
    "team background": "Who are we?",
    "what is empire of shadows": "Who are we?",

    # What we offer - Embed
    "what we offer": "What we offer",
    "what do you offer": "What we offer",
    "what can I get": "What we offer",
    "what can we do": "What we offer",
    "what are the features": "What we offer",
    "what’s included": "What we offer",
    "what is available": "What we offer",
    "our offer": "What we offer",
    "offerings": "What we offer",
    "what does the server have": "What we offer",
    "server features": "What we offer",
    "server perks": "What we offer",
    "why should I join": "What we offer",
    "what's in it for me": "What we offer",

    # Our Store - Embed
    "our store": "Our Store",
    "buy items": "Our Store",
    "buy stuff": "Our Store",
    "where is the store": "Our Store",
    "how to buy": "Our Store",
    "purchase things": "Our Store",
    "shop": "Our Store",
    "store page": "Our Store",
    "how to spend currency": "Our Store",
    "use server coins": "Our Store",
    "buy roles": "Our Store",
    "server shop": "Our Store",
    "in-server store": "Our Store",
    "economy shop": "Our Store",
    "where to spend points": "Our Store",
    "what can I buy": "Our Store",
    "buy items and roles": "Our Store",
    "buy a role": "Our Store",

    # 🎯 Basic Server Guidelines
    "basic rules": "Basic Server Guidelines",
    "server rules": "Basic Server Guidelines",
    "community rules": "Basic Server Guidelines",
    "general rules": "Basic Server Guidelines",
    "core rules": "Basic Server Guidelines",
    "main rules": "Basic Server Guidelines",
    "what are the server rules": "Basic Server Guidelines",
    "what should i avoid": "Basic Server Guidelines",
    "basic conduct": "Basic Server Guidelines",
    "rule summary": "Basic Server Guidelines",
    "what's allowed": "Basic Server Guidelines",
    "what’s not allowed": "Basic Server Guidelines",
    "chat rules": "Basic Server Guidelines",
    "channel rules": "Basic Server Guidelines",

    # 🎶 Music Bot Guidelines
    "music rules": "Music Bot Guidelines",
    "bot music rules": "Music Bot Guidelines",
    "rules for music": "Music Bot Guidelines",
    "music guidelines": "Music Bot Guidelines",
    "how to use music": "Music Bot Guidelines",
    "music spam rules": "Music Bot Guidelines",
    "bot usage for music": "Music Bot Guidelines",
    "jukebox rules": "Music Bot Guidelines",
    "music limitations": "Music Bot Guidelines",
    "audio bot rules": "Music Bot Guidelines",

    # 🎮 Game Guidelines
    "Game Guidelines": "Game Guidelines",
    "rules for games": "Game Guidelines",
    "gameplay rules": "Game Guidelines",
    "game bot rules": "Game Guidelines",
    "uno rules": "Game Guidelines",
    "hangman rules": "Game Guidelines",
    "rules for bot games": "Game Guidelines",
    "rules for events": "Game Guidelines",
    "gaming rules": "Game Guidelines",
    "multiplayer rules": "Game Guidelines",
    "play rules": "Game Guidelines",

    # Guidelines - Select
    "rules": "Guidelines",
    "server guidelines": "Guidelines",
    "discord rules": "Guidelines",
    "terms of service": "Guidelines",
    "code of conduct": "Guidelines",
    "posting rules": "Guidelines",
    "acceptable behavior": "Guidelines",
    "server dos and don'ts": "Guidelines",

    # Getting Started - Menu
    "getting started": "Getting Started",
    "getting started guide": "Getting Started",
    "new user guide": "Getting Started",
    "getting started tutorial": "Getting Started",
    "how to start": "Getting Started",
    "how to use": "Getting Started",
    "beginner's guide": "Getting Started",
    "start here": "Getting Started",
    "getting started FAQ": "Getting Started",
    "start guide": "Getting Started",
    "setup instructions": "Getting Started",
    "welcome guide": "Getting Started",
    "introduction": "Getting Started",
    "how it works": "Getting Started",
    "new member guide": "Getting Started",
    "first steps": "Getting Started",
    "starting out": "Getting Started",
    "quick start": "Getting Started",
    "quick start guide": "Getting Started",
    "how to join": "Getting Started",
    "server steps": "Getting Started",
    "server guide": "Getting Started",
    "beginner help": "Getting Started",
    "tutorial": "Getting Started",

    # Announcements - Embed
    "announcements": "Announcements",
    "where are the announcements": "Announcements",
    "latest announcements": "Announcements",
    "any announcements": "Announcements",
    "where can I find updates": "Announcements",
    "news": "Announcements",
    "any server news": "Announcements",
    "did anything change": "Announcements",
    "updates": "Announcements",
    "server update": "Announcements",
    "did the server change": "Announcements",
    "server news": "Announcements",
    "news and announcements": "Announcements",
    "what's the latest": "Announcements",
    "official updates": "Announcements",
    "what's been posted": "Announcements",
    "latest updates": "Announcements",
    "server updates": "Announcements",
    "event updates": "Announcements",
    "breaking news": "Announcements",
    "important updates": "Announcements",
    "what's new": "Announcements",
    "recent news": "Announcements",
    "server announcements": "Announcements",
    "latest news": "Announcements",
    "ongoing events": "Announcements",
    "community updates": "Announcements",
    "announcement channel": "Announcements",
    "news board": "Announcements",
    "new events": "Announcements",
    "new features": "Announcements",
    "updates and news": "Announcements",
    "future updates": "Announcements",
    "is there anything new": "Announcements",
    "did anything get posted": "Announcements",
    "has anything changed": "Announcements",

    # React - Embed
    "role selection": "Roles",
    "reaction roles": "Roles",
    "where do I get roles": "Roles",
    "how do I choose roles": "Roles",
    "get roles": "Roles",
    "how to get roles": "Roles",
    "assign roles": "Roles",
    "role settings": "Roles",
    "can I pick a role": "Roles",
    "role picker": "Roles",
    "how do roles work": "Roles",
    "self-assign roles": "Roles",
    "role information": "Roles",
    "how do I assign a role": "Roles",
    "channel roles": "Roles",
    "select your roles": "Roles",
    "react to get a role": "Roles",
    "reaction instructions": "Roles",
    "choose a role": "Roles",
    "role setup": "Roles",
    "role guide": "Roles",
    "reaction-based roles": "Roles",
    "can I remove a role": "Roles",
    "how to react": "Roles",
    "how to get access": "Roles",
    "how do I join a role": "Roles",
    "how to unlock stuff": "Roles",
    "where is the role board": "Roles",
    "how to choose notification roles": "Roles",

    # Forum - Embed
    "forum": "Forum",
    "forums": "Forum",
    "where can I ask for help": "Forum",
    "community forum": "Forum",
    "can I post a question": "Forum",
    "discussion boards": "Forum",
    "discussion forum": "Forum",
    "is there a help section": "Forum",
    "online forum": "Forum",
    "user forum": "Forum",
    "where to post tips": "Forum",
    "forum threads": "Forum",
    "community discussions": "Forum",
    "community support": "Forum",
    "help center": "Forum",
    "peer advice": "Forum",
    "how do I ask something": "Forum",
    "knowledge sharing": "Forum",
    "qa forum": "Forum",
    "group discussions": "Forum",
    "troubleshooting hub": "Forum",
    "knowledge base": "Forum",
    "message boards": "Forum",
    "discussion topics": "Forum",
    "problem-solving space": "Forum",
    "tips and tricks": "Forum",
    "interactive discussions": "Forum",
    "support channel": "Forum",
    "community space": "Forum",
    "ideas exchange": "Forum",
    "collaborative discussions": "Forum",
    "insights and advice": "Forum",
    "forum archives": "Forum",
    "problem solvers network": "Forum",
    "how do I get help": "Forum",
    "can I get tech support": "Forum",
    "where can I post something helpful": "Forum",
    "any way to ask a question": "Forum",

    # Commands - Menu
    "commands": "Commands",
    "command": "Commands",
    "how do I use the bot": "Commands",
    "bot help": "Commands",
    "command list": "Commands",
    "available commands": "Commands",
    "bot commands": "Commands",
    "how do commands work": "Commands",
    "command reference": "Commands",
    "command guide": "Commands",
    "what are the bot commands": "Commands",
    "how to use commands": "Commands",
    "command help": "Commands",
    "server commands": "Commands",
    "command help list": "Commands",
    "bot command list": "Commands",
    "what can I type": "Commands",
    "user commands": "Commands",
    "commands menu": "Commands",
    "command options": "Commands",
    "list of commands": "Commands",
    "bot command guide": "Commands",
    "help with commands": "Commands",
    "all commands": "Commands",
    "supported commands": "Commands",
    "command menu list": "Commands",
    "bot help menu": "Commands",
    "command selection": "Commands",
    "custom commands": "Commands",
    "commands overview": "Commands",
    "menu of commands": "Commands",
    "interactive commands": "Commands",
    "command shortcuts": "Commands",
    "control commands": "Commands",
    "feature commands": "Commands",
    "bot functionalities": "Commands",
    "available bot options": "Commands",
    "how to interact with bot": "Commands",
    "how do I do stuff": "Commands",
    "how does this work": "Commands",
    "bot options": "Commands",
    "help menu": "Commands",
    "where are the bot commands": "Commands",
    "can I see all commands": "Commands",
    "how do I make the bot do something": "Commands",
    "how do I get started": "Commands",
    "bot features": "Commands",

    # The Imperial Host - Embed
    "hangman": "The Imperial Host",
    "hang man": "The Imperial Host",
    "tictactoe": "The Imperial Host",
    "tic tac toe": "The Imperial Host",
    "tic-tac-toe": "The Imperial Host",
    "game guide": "The Imperial Host",
    "game instructions": "The Imperial Host",
    "how to play hangman": "The Imperial Host",
    "how to play tictactoe": "The Imperial Host",
    "how to play games": "The Imperial Host",
    "hangman guide": "The Imperial Host",
    "hangman help": "The Imperial Host",
    "tictactoe help": "The Imperial Host",
    "tic tac toe help": "The Imperial Host",
    "tic-tac-toe guide": "The Imperial Host",
    "game help": "The Imperial Host",
    "game tips": "The Imperial Host",
    "how to play games on server": "The Imperial Host",
    "interactive games": "The Imperial Host",
    "leaderboard guide": "The Imperial Host",
    "rival command": "The Imperial Host",
    "how to find rival": "The Imperial Host",
    "game leaderboard": "The Imperial Host",
    "server features guide": "The Imperial Host",
    "gameplay instructions": "The Imperial Host",

    # The Imperial Host - Menu

    # Pokétwo - Start / Basics
    "how to start poketwo": "Start playing PokéTwo",
    "start poketwo adventure": "Start playing PokéTwo",
    "poketwo starter": "Start playing PokéTwo",
    "pick starter poketwo": "Start playing PokéTwo",
    "begin poketwo": "Start playing PokéTwo",
    "poketwo help": "Start playing PokéTwo",
    "how to play poketwo": "Start playing PokéTwo",
    "poketwo basics": "Start playing PokéTwo",
    "poketwo getting started": "Start playing PokéTwo",
    "poketwo commands": "Start playing PokéTwo",

    # Pokétwo - Catching and Info Commands
    "how to catch pokemon": "Start playing PokéTwo",
    "poketwo catch": "Start playing PokéTwo",
    "poketwo hint": "Start playing PokéTwo",
    "poketwo shinyhunt": "Start playing PokéTwo",
    "poketwo evolve": "Start playing PokéTwo",
    "poketwo nickname": "Start playing PokéTwo",
    "poketwo order": "Start playing PokéTwo",
    "poketwo select": "Start playing PokéTwo",
    "poketwo pokedex": "Start playing PokéTwo",
    "poketwo release": "Start playing PokéTwo",
    "poketwo info": "Start playing PokéTwo",

    # Pokétwo - Battle
    "poketwo battle": "Pokétwo Battle Commands",
    "poketwo duel": "Pokétwo Battle Commands",
    "battle user poketwo": "Pokétwo Battle Commands",
    "poketwo battle add": "Pokétwo Battle Commands",
    "cancel poketwo battle": "Pokétwo Battle Commands",
    "poketwo learn move": "Pokétwo Battle Commands",
    "poketwo moveset": "Pokétwo Battle Commands",
    "poketwo moveinfo": "Pokétwo Battle Commands",
    "pokemon battle moves": "Pokétwo Battle Commands",

    # Pokétwo - Other / Misc
    "poketwo auction": "Pokétwo Misc Commands",
    "poketwo daily": "Pokétwo Misc Commands",
    "poketwo vote": "Pokétwo Misc Commands",
    "poketwo profile": "Pokétwo Misc Commands",
    "poketwo prefix": "Pokétwo Misc Commands",
    "poketwo open box": "Pokétwo Misc Commands",
    "poketwo box": "Pokétwo Misc Commands",
    "poketwo event": "Pokétwo Misc Commands",
    "poketwo embedcolor": "Pokétwo Misc Commands",
    "poketwo server silence": "Pokétwo Misc Commands",
    "poketwo next": "Pokétwo Misc Commands",
    "poketwo back": "Pokétwo Misc Commands",
    "poketwo time": "Pokétwo Misc Commands",

    # Pokétwo - Menu Fallback (catch-all)
    "poketwo": "Pokétwo",
    "poketwo commands list": "Pokétwo",
    "poketwo guide": "Pokétwo",
    "what is poketwo": "Pokétwo",
    "poketwo game": "Pokétwo",

    # 🎉 Basic commands Commands
    "set birthday": "Basic commands",
    "remember birthday": "Basic commands",
    "birthday command": "Basic commands",
    "forget birthday": "Basic commands",
    "view birthdays": "Basic commands",
    "next birthday": "Basic commands",
    "color role command": "Basic commands",
    "remove color role": "Basic commands",
    "ember economy": "Basic commands",

    # 🧾 Server commands and Search commands Info and Search
    "role info": "Server commands and Search commands",
    "server info": "Server commands and Search commands",
    "user info": "Server commands and Search commands",
    "view server": "Server commands and Search commands",
    "get server info": "Server commands and Search commands",
    "level leaderboard": "Server commands and Search commands",
    "user rank": "Server commands and Search commands",
    "rank command": "Server commands and Search commands",
    "search anime": "Server commands and Search commands",
    "anime command": "Server commands and Search commands",
    "search manga": "Server commands and Search commands",
    "manga command": "Server commands and Search commands",
    "search twitch": "Server commands and Search commands",
    "search youtube": "Server commands and Search commands",
    "search pokemon": "Server commands and Search commands",
    "imgur search": "Server commands and Search commands",

    # 🎮 Velarion Fun and Games
    "music quiz": "Fun and games",
    "start quiz": "Fun and games",
    "stop quiz": "Fun and games",
    "server games": "Fun and games",
    "play games": "Fun and games",
    "dice game": "Fun and games",
    "guess number": "Fun and games",
    "rps game": "Fun and games",
    "rock paper scissors": "Fun and games",
    "roulette game": "Fun and games",
    "info games": "Fun and games",

    # 💰 Economy Information Information
    "buy item": "Economy Information",
    "daily coins": "Economy Information",
    "economy info": "Economy Information",
    "coin info": "Economy Information",
    "give item": "Economy Information",
    "use item": "Economy Information",
    "view shop": "Economy Information",
    "shop command": "Economy Information",
    "inventory list": "Economy Information",
    "richest players": "Economy Information",
    "work command": "Economy Information",
    "get embers": "Economy Information",

    # 📜 Velarion - Menu (Catch-all)
    "velarion commands": "Velarion",
    "velarion help": "Velarion",
    "velarion guide": "Velarion",
    "how to use velarion": "Velarion",
    "velarion bot": "Velarion",

    # Living Room & The Room - Embed
    "living room music": "Living Room & The Room",
    "the room music": "Living Room & The Room",
    "living room bot": "Living Room & The Room",
    "the room bot": "Living Room & The Room",
    "play music in living room": "Living Room & The Room",
    "play music in the room": "Living Room & The Room",
    "add song to living room": "Living Room & The Room",
    "add song to the room": "Living Room & The Room",
    "search song in living room": "Living Room & The Room",
    "search song in the room": "Living Room & The Room",
    "living room queue": "Living Room & The Room",
    "the room queue": "Living Room & The Room",
    "living room commands": "Living Room & The Room",
    "the room commands": "Living Room & The Room",
    "living room guide": "Living Room & The Room",
    "the room guide": "Living Room & The Room",

    # Expanded terms based on command usage
    "living room play song": "Living Room & The Room",
    "the room play song": "Living Room & The Room",
    "living room playlist": "Living Room & The Room",
    "the room playlist": "Living Room & The Room",
    "living room artist": "Living Room & The Room",
    "the room artist": "Living Room & The Room",
    "living room now playing": "Living Room & The Room",
    "the room now playing": "Living Room & The Room",
    "living room loop": "Living Room & The Room",
    "the room loop": "Living Room & The Room",
    "living room clear": "Living Room & The Room",
    "the room clear": "Living Room & The Room",
    "clear queue in living room": "Living Room & The Room",
    "clear queue in the room": "Living Room & The Room",
    "move song in living room": "Living Room & The Room",
    "move song in the room": "Living Room & The Room",
    "remove song from living room": "Living Room & The Room",
    "remove song from the room": "Living Room & The Room",
    "living room help": "Living Room & The Room",
    "the room help": "Living Room & The Room",
    "music commands for living room": "Living Room & The Room",
    "music commands for the room": "Living Room & The Room",


    # MusicMan - Embed
    "musicman": "MusicMan",
    "musicman bot": "MusicMan",
    "musicman commands": "MusicMan",
    "musicman play": "MusicMan",
    "musicman pause": "MusicMan",
    "musicman resume": "MusicMan",
    "musicman skip": "MusicMan",
    "musicman volume": "MusicMan",
    "musicman shuffle": "MusicMan",
    "musicman leave": "MusicMan",
    "musicman 24/7": "MusicMan",
    "musicman playlist": "MusicMan",
    "musicman create playlist": "MusicMan",
    "musicman manage playlist": "MusicMan",
    "musicman remove playlist": "MusicMan",
    "musicman radio": "MusicMan",
    "musicman fast forward": "MusicMan",
    "musicman rewind": "MusicMan",
    "musicman queue": "MusicMan",
    "musicman clear queue": "MusicMan",
    "musicman jump": "MusicMan",
    "musicman recently played": "MusicMan",
    "musicman effects": "MusicMan",
    "musicman loop": "MusicMan",
    "musicman crossfade": "MusicMan",
    "musicman party": "MusicMan",
    "musicman admin": "MusicMan",
    "musicman permissions": "MusicMan",
    "musicman disable": "MusicMan",
    "musicman server": "MusicMan",
    "musicman issues": "MusicMan",
    "musicman help": "MusicMan",
    "musicman report": "MusicMan",

    # Music Bots - Menu
    "music": "Music Bots",
    "music bots": "Music Bots",
    "music bot": "Music Bots",
    "music commands": "Music Bots",
    "music bot commands": "Music Bots",
    "music playlist": "Music Bots",
    "play music": "Music Bots",
    "stream music": "Music Bots",
    "music setup": "Music Bots",
    "music guide": "Music Bots",
    "pause music": "Music Bots",
    "resume music": "Music Bots",
    "stop music": "Music Bots",
    "queue music": "Music Bots",
    "next song": "Music Bots",
    "music volume": "Music Bots",
    "music control": "Music Bots",

    # Categories and Channels - Menu
    "categories and channels": "Categories and Channels",
    "categories and channels menu": "Categories and Channels",
    "categories and channels guide": "Categories and Channels",
    "categories and channels list": "Categories and Channels",
    "categories menu": "Categories and Channels",
    "game categories": "Categories and Channels",
    "channel categories": "Categories and Channels",
    "list of categories": "Categories and Channels",
    "list of channels": "Categories and Channels",
    "categories guide": "Categories and Channels",
    "channel guide": "Categories and Channels",
    "channel list": "Categories and Channels",
    "categories and menu options": "Categories and Channels",

    # Updates and Drops - Menu
    "updates and drops": "Updates and Drops",
    "updates menu": "Updates and Drops",
    "drops menu": "Updates and Drops",
    "twitch drops": "Updates and Drops",
    "free games and updates": "Updates and Drops",
    "announcement updates": "Updates and Drops",
    "gaming updates": "Updates and Drops",
    "game news and drops": "Updates and Drops",
    "special rewards and drops": "Updates and Drops",
    "limited-time drops": "Updates and Drops",

    # 🛠│game-updates│ - Embed
    "game updates": "🛠│game-updates│",
    "game announcements": "🛠│game-updates│",
    "latest game news": "🛠│game-updates│",
    "game update feed": "🛠│game-updates│",
    "updates on games": "🛠│game-updates│",
    "news and updates": "🛠│game-updates│",
    "news about games": "🛠│game-updates│",
    "stay updated on games": "🛠│game-updates│",
    "game update announcements": "🛠│game-updates│",
    "check game updates": "🛠│game-updates│",
    "choose game roles": "🛠│game-updates│",
    "game roles": "🛠│game-updates│",
    "update my games": "🛠│game-updates│",
    "game roles and updates": "🛠│game-updates│",

    # 📢│freebies│🤩 - Embed
    "free games": "📢│freebies│🤩",
    "games free": "📢│freebies│🤩",
    "free gaming": "📢│freebies│🤩",
    "gaming free": "📢│freebies│🤩",
    "no-cost games": "📢│freebies│🤩",
    "freebies games": "📢│freebies│🤩",
    "free entertainment": "📢│freebies│🤩",
    "gamers deal": "📢│freebies│🤩",
    "free PC games": "📢│freebies│🤩",
    "free console games": "📢│freebies│🤩",
    "free video games": "📢│freebies│🤩",
    "free digital games": "📢│freebies│🤩",
    "100% free games": "📢│freebies│🤩",
    "free-to-play games": "📢│freebies│🤩",

    # 🪂│prime-drops│🪂 - Embed
    "prime drops": "🪂│prime-drops│🪂",
    "prime gaming": "🪂│prime-drops│🪂",
    "amazon prime drops": "🪂│prime-drops│🪂",
    "twitch rewards": "🪂│prime-drops│🪂",
    "prime gaming rewards": "🪂│prime-drops│🪂",
    "prime gaming drops": "🪂│prime-drops│🪂",
    "twitch gaming drops": "🪂│prime-drops│🪂",
    "amazon rewards": "🪂│prime-drops│🪂",
    "claimed twitch drops": "🪂│prime-drops│🪂",
    "twitch prime freebies": "🪂│prime-drops│🪂",
    "exclusive drops": "🪂│prime-drops│🪂",
    "prime loot": "🪂│prime-drops│🪂",
    "amazon gaming rewards": "🪂│prime-drops│🪂",
    "twitch prime": "🪂│prime-drops│🪂",
    "rewards and drops": "🪂│prime-drops│🪂",
    "twitch gaming rewards": "🪂│prime-drops│🪂",
    "prime deals": "🪂│prime-drops│🪂",

    # General Channels - Menu
    "general channels": "General Channels",
    "non-game chat": "General Channels",
    "social channels": "General Channels",
    "casual discussion": "General Channels",
    "general discussion": "General Channels",
    "non-gaming chat": "General Channels",
    "general text chat": "General Channels",
    "social chat rooms": "General Channels",
    "casual hangout": "General Channels",
    "memes and media channel": "General Channels",
    "meme sharing": "General Channels",
    "text and voice channels": "General Channels",
    "general voice chat": "General Channels",
    "funny media channel": "General Channels",
    "chat for everything": "General Channels",
    "chill chat spaces": "General Channels",
    "lighthearted channels": "General Channels",
    "channels for everyone": "General Channels",

    # 🧖│living-room│🛋 - Embed
    "living room chat": "🧖│living-room│🛋",
    "casual chat room": "🧖│living-room│🛋",
    "hangout spot": "🧖│living-room│🛋",
    "general chat": "🧖│living-room│🛋",
    "friendly chat room": "🧖│living-room│🛋",
    "ultimate casual hangout": "🧖│living-room│🛋",
    "random chit-chat": "🧖│living-room│🛋",
    "laid-back chat": "🧖│living-room│🛋",
    "daily life updates": "🧖│living-room│🛋",
    "exchange ideas chat": "🧖│living-room│🛋",
    "talk about hobbies": "🧖│living-room│🛋",
    "text room for everyone": "🧖│living-room│🛋",
    "relaxed conversations": "🧖│living-room│🛋",
    "off-topic chat": "🧖│living-room│🛋",
    "life discussion space": "🧖│living-room│🛋",
    "favorite shows chat": "🧖│living-room│🛋",
    "open-topic chat": "🧖│living-room│🛋",
    "movie discussions": "🧖│living-room│🛋",
    "friendly hangout space": "🧖│living-room│🛋",
    "community bonding chat": "🧖│living-room│🛋",

    # 🙈│memes⅋media│🙈 - Embed
    "memes and media": "🙈│memes⅋media│🙈",
    "media sharing": "🙈│memes⅋media│🙈",
    "meme channel": "🙈│memes⅋media│🙈",
    "funny memes": "🙈│memes⅋media│🙈",
    "media channel": "🙈│memes⅋media│🙈",
    "funny videos": "🙈│memes⅋media│🙈",
    "random media": "🙈│memes⅋media│🙈",
    "hilarious memes": "🙈│memes⅋media│🙈",
    "creative media": "🙈│memes⅋media│🙈",
    "video clips": "🙈│memes⅋media│🙈",
    "fun content": "🙈│memes⅋media│🙈",
    "random fun": "🙈│memes⅋media│🙈",
    "cool media": "🙈│memes⅋media│🙈",
    "share memes": "🙈│memes⅋media│🙈",
    "post cool videos": "🙈│memes⅋media│🙈",
    "laugh and share": "🙈│memes⅋media│🙈",
    "entertainment channel": "🙈│memes⅋media│🙈",
    "lighthearted media": "🙈│memes⅋media│🙈",
    "funny internet finds": "🙈│memes⅋media│🙈",
    "share creative content": "🙈│memes⅋media│🙈",

    # 🛋│Living Room│ - Embed
    "living room voice chat": "🛋│Living Room│",
    "voice channel": "🛋│Living Room│",
    "relaxed voice chat": "🛋│Living Room│",
    "chill voice channel": "🛋│Living Room│",
    "casual voice conversations": "🛋│Living Room│",
    "hangout voice chat": "🛋│Living Room│",
    "laid-back voice channel": "🛋│Living Room│",
    "music and chat": "🛋│Living Room│",
    "background tunes voice chat": "🛋│Living Room│",
    "friendly chats": "🛋│Living Room│",
    "vibe with music": "🛋│Living Room│",
    "voice room for stories": "🛋│Living Room│",
    "relaxed hangout spot": "🛋│Living Room│",
    "daily chat voice room": "🛋│Living Room│",
    "catch up conversations": "🛋│Living Room│",
    "community voice hangout": "🛋│Living Room│",
    "chill and talk": "🛋│Living Room│",
    "voice chat with tunes": "🛋│Living Room│",
    "vibing space voice channel": "🛋│Living Room│",
    "work and voice chat": "🛋│Living Room│",

    # Gaming - Menu
    "gaming hub": "Gaming",
    "game-related content": "Gaming",
    "game discussions": "Gaming",
    "gaming channels": "Gaming",
    "discuss gaming": "Gaming",
    "connect with gamers": "Gaming",
    "gaming community": "Gaming",
    "game tips and strategies": "Gaming",
    "gaming fanatics": "Gaming",

    # 💺│gaming-chair│💺 - Embed
    "gaming discussions": "💺│gaming-chair│💺",
    "favorite games chat": "💺│gaming-chair│💺",
    "game talk": "💺│gaming-chair│💺",
    "talk about games": "💺│gaming-chair│💺",
    "game strategies": "💺│gaming-chair│💺",
    "recommend games": "💺│gaming-chair│💺",
    "latest gaming trends": "💺│gaming-chair│💺",
    "casual gaming chat": "💺│gaming-chair│💺",
    "hardcore gaming discussion": "💺│gaming-chair│💺",
    "find fellow gamers": "💺│gaming-chair│💺",

    # 🛋│Game Media│ - Embed
    "game media sharing": "🛋│Game Media│",
    "post gaming screenshots": "🛋│Game Media│",
    "share gaming achievements": "🛋│Game Media│",
    "epic game moments": "🛋│Game Media│",
    "amazing game videos": "🛋│Game Media│",
    "fun gaming memes": "🛋│Game Media│",
    "show off gaming moments": "🛋│Game Media│",
    "share proud gaming achievements": "🛋│Game Media│",
    "gaming highlights section": "🛋│Game Media│",
    "celebrate gaming wins": "🛋│Game Media│",

    # 🛏│The Room│🛏 - Embed
    "gaming voice chat": "🛏│The Room│🛏",
    "game strategy voice chat": "🛏│The Room│🛏",
    "game discussion voice room": "🛏│The Room│🛏",
    "hang out with players": "🛏│The Room│🛏",
    "relaxed game voice chat": "🛏│The Room│🛏",
    "voice room for gamers": "🛏│The Room│🛏",
    "chill between matches": "🛏│The Room│🛏",
    "game vibe voice channel": "🛏│The Room│🛏",
    "epic gaming voice chat": "🛏│The Room│🛏",
    "music and games voice room": "🛏│The Room│🛏",

    # Attribution - Menu
    "bot resources": "Attribution",
    "reference materials": "Attribution",
    "resources used": "Attribution",
    "app creation credits": "Attribution",
    "tools and APIs": "Attribution",
    "attribution details": "Attribution",
    "credits and mentions menu": "Attribution",
    "how this bot works": "Attribution",

    # GamerPower - Embed
    "free game deals": "GamerPower",
    "free games platform": "GamerPower",
    "game discounts": "GamerPower",
    "gamerpower API": "GamerPower",
    "find free games": "GamerPower",
    "game notification setup": "GamerPower",
    "game deals site": "GamerPower",
    "discount gaming services": "GamerPower",
    "gamerpower documentation": "GamerPower",
    "gaming platform deals": "GamerPower",

    # SteamAPI - Embed
    "steamAPI game info": "SteamAPI",
    "steam API docs": "SteamAPI",
    "find game details": "SteamAPI",
    "game data through API": "SteamAPI",
    "API for games": "SteamAPI",
    "steam community API": "SteamAPI",
    "steam game information": "SteamAPI",
    "game-related APIs": "SteamAPI",
    "steam developer tools": "SteamAPI",
    "connect to steam API": "SteamAPI",

    # Honorable Mentions - Embed
    "additional resources": "Honorable Mentions",
    "credits and mentions": "Honorable Mentions",
    "other tools used": "Honorable Mentions",
    "helper resources": "Honorable Mentions",
    "secondary credits": "Honorable Mentions",
    "unspecified mentions": "Honorable Mentions",
    "future additions": "Honorable Mentions",
    "resources to be listed": "Honorable Mentions",

}


# Help-related keywords for a generic help response
HELP_WORDS = {
    "help",
    "assistance",
    "guidance",
    "support",
    "info",
    "information",
    "instructions",
    "how to",
    "manual",
    "faq",
    "troubleshoot",
    "troubleshooting",
    "guide",
    "explanation",
    "overview",
    "help menu",
    "usage",
    "tips",
    "learn",
    "details",
    "advice",
    "solution",
    "issues",
}




